services:

  web-app:
    user: "1000:1000"
    build:
      context: ../../app
    volumes:
      - ../../app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - ylab_web
    command: python3 main.py

networks:
  ylab_web:
    name: ylab_web
    external: false