version: "3.8"

services:

  web-app:
    user: "1000:1000"
    build:
      context: ../../app
    volumes:
      - ../../app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - ylab_web
#    command: python3 main.py
    entrypoint: sh -c "alembic upgrade head && python3 main.py"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - ylab_web
    volumes:
      - menu-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  test:
    user: "1000:1000"
    build:
      context: ../../test
    volumes:
      - ../../test:/test
    env_file:
      - .env
    networks:
      - ylab_web
    entrypoint: sh -c "pytest -v"

volumes:
  menu-db:


networks:
  ylab_web:
    name: ylab_web
    external: false