version: "3.8"

services:

  web-app:
    user: "1000:1000"
    build:
      context: ../../app
    volumes:
      - ../../app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - ylab_web
#    command: python3 main.py
    entrypoint: sh -c "alembic upgrade head && python3 main.py"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - ylab_web
    volumes:
      - menu-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    networks:
        - ylab_web
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 40s

  celery:
    build:
      context: ../../db_updater/
    volumes:
      - ../../db_updater:/db_updater
      - ../../admin:/admin
    depends_on:
      rabbitmq:
        condition: service_healthy
      web-app:
        condition: service_started
    networks:
      - ylab_web
    env_file:
      - .env
    entrypoint: sh -c "celery -A task worker -B --loglevel=INFO"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - .env
    networks:
      - ylab_web
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 20s
      retries: 3

volumes:
  menu-db:


networks:
  ylab_web:
    name: ylab_web
    external: false
